name: risk-worker

services:
  risk-postgres:
    image: postgres:16.9-alpine
    env_file:
      - .env.docker.postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U risk_user -d risk_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - risk-worker-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - risk-worker-network

  risk-worker:
    build: .
    env_file:
      - .env.production
    ports:
      - "8000:8000"
    depends_on:
      risk-postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - risk-worker-network

volumes:
  postgres_data: 

networks:
  risk-worker-network:
    driver: bridge